// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgcwtnrimreruswogffr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnY3d0bnJpbXJlcnVzd29nZmZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzODU2MDYsImV4cCI6MjA4NDk2MTYwNn0.oUn-P4PZ5HOJd-qiAVjCRZ_QToQzQk1ZpAxiktVT4sA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});